import { TemplateConfig } from '../types/template'

export const announcementTemplate: TemplateConfig = {
  id: 'announcement',
  name: 'Aankondiging',
  description: 'Voor evenementen en aankondigingen',
  backgroundColor: '#1F3A4A',
  fields: [
    {
      id: 'title',
      label: 'Titel',
      type: 'text',
      required: true,
      maxLength: 60,
      maxFontSize: 56,
      minFontSize: 36,
      x: 80,
      y: 100,
      width: 920,
      height: 90,
      fontFamily: 'FF DIN',
      fontWeight: '700',
      color: '#00B4CC',
      textAlign: 'center',
    },
    {
      id: 'description',
      label: 'Beschrijving',
      type: 'multiline',
      required: true,
      maxFontSize: 28,
      minFontSize: 16,
      x: 100,
      y: 220,
      width: 880,
      height: 240,
      fontFamily: 'FF DIN',
      fontWeight: '500',
      color: '#FFFFFF',
      textAlign: 'center',
      lineHeight: 1.5,
    },
    {
      id: 'cta',
      label: 'Call-to-action',
      type: 'text',
      required: false,
      maxLength: 50,
      fontSize: 26,
      x: 80,
      y: 510,
      width: 920,
      height: 50,
      fontFamily: 'FF DIN',
      fontWeight: '700',
      color: '#FFC107',
      textAlign: 'center',
    },
    {
      id: 'footer',
      label: 'Voettekst',
      type: 'text',
      required: false,
      maxLength: 100,
      fontSize: 14,
      x: 80,
      y: 920,
      width: 920,
      height: 30,
      fontFamily: 'FF DIN',
      fontWeight: '400',
      color: '#88888A',
      textAlign: 'center',
    },
  ],
  logo: {
    text: '●',
    x: 515,
    y: 710,
    fontSize: 36,
    color: '#00B4CC',
  },
}
