import { TemplateConfig } from '../types/template'

export const announcementTemplate: TemplateConfig = {
  id: 'announcement',
  name: 'Aankondiging',
  description: 'Voor evenementen en aankondigingen',
  backgroundColor: '#2C3E50',
  fields: [
    {
      id: 'title',
      label: 'Titel',
      type: 'text',
      required: true,
      maxLength: 60,
      maxFontSize: 52,
      minFontSize: 36,
      x: 60,
      y: 100,
      width: 960,
      height: 80,
      fontFamily: 'FF DIN',
      fontWeight: '700',
      color: '#3498DB',
      textAlign: 'center',
    },
    {
      id: 'description',
      label: 'Beschrijving',
      type: 'multiline',
      required: true,
      maxFontSize: 28,
      minFontSize: 16,
      x: 100,
      y: 220,
      width: 880,
      height: 250,
      fontFamily: 'FF DIN',
      fontWeight: '400',
      color: '#FFFFFF',
      textAlign: 'center',
      lineHeight: 1.5,
    },
    {
      id: 'cta',
      label: 'Call-to-action',
      type: 'text',
      required: false,
      maxLength: 50,
      fontSize: 24,
      x: 60,
      y: 530,
      width: 960,
      height: 50,
      fontFamily: 'FF DIN',
      fontWeight: '700',
      color: '#F39C12',
      textAlign: 'center',
    },
    {
      id: 'footer',
      label: 'Voettekst',
      type: 'text',
      required: false,
      maxLength: 100,
      fontSize: 16,
      x: 60,
      y: 920,
      width: 960,
      height: 30,
      fontFamily: 'FF DIN',
      fontWeight: '400',
      color: '#95A5A6',
      textAlign: 'center',
    },
  ],
  logo: {
    text: '★',
    x: 470,
    y: 700,
    fontSize: 32,
    color: '#3498DB',
  },
}
