import { TemplateConfig } from '../types/template'

export const breakingTemplate: TemplateConfig = {
  id: 'breaking',
  name: 'Breaking News',
  description: 'Voor nieuws en breaking stories',
  backgroundColor: '#FF4444',
  fields: [
    {
      id: 'headline',
      label: 'Kop/Headline',
      type: 'multiline',
      required: true,
      maxFontSize: 56,
      minFontSize: 32,
      x: 60,
      y: 80,
      width: 960,
      height: 300,
      fontFamily: 'FF DIN',
      fontWeight: '700',
      color: '#FFFFFF',
      textAlign: 'left',
      lineHeight: 1.2,
    },
    {
      id: 'subtitle',
      label: 'Ondertitel',
      type: 'multiline',
      required: true,
      maxFontSize: 32,
      minFontSize: 18,
      x: 60,
      y: 400,
      width: 960,
      height: 200,
      fontFamily: 'FF DIN',
      fontWeight: '400',
      color: '#FFFFFF',
      textAlign: 'left',
      lineHeight: 1.3,
    },
    {
      id: 'date',
      label: 'Datum',
      type: 'text',
      required: false,
      maxLength: 50,
      fontSize: 16,
      x: 60,
      y: 920,
      width: 400,
      height: 30,
      fontFamily: 'FF DIN',
      fontWeight: '400',
      color: '#FFFFCC',
      textAlign: 'left',
    },
  ],
  logo: {
    text: 'BREAKING',
    x: 900,
    y: 100,
    fontSize: 24,
    color: '#FFFFFF',
  },
}
