import { TemplateConfig } from '../types/template'

export const breakingTemplate: TemplateConfig = {
  id: 'breaking',
  name: 'Breaking News',
  description: 'Voor nieuws en breaking stories',
  backgroundColor: '#D32F2F',
  fields: [
    {
      id: 'headline',
      label: 'Kop/Headline',
      type: 'multiline',
      required: true,
      maxFontSize: 64,
      minFontSize: 36,
      x: 70,
      y: 100,
      width: 940,
      height: 280,
      fontFamily: 'FF DIN',
      fontWeight: '700',
      color: '#FFFFFF',
      textAlign: 'left',
      lineHeight: 1.1,
    },
    {
      id: 'subtitle',
      label: 'Ondertitel',
      type: 'multiline',
      required: true,
      maxFontSize: 32,
      minFontSize: 18,
      x: 70,
      y: 410,
      width: 940,
      height: 180,
      fontFamily: 'FF DIN',
      fontWeight: '500',
      color: '#FFFFFF',
      textAlign: 'left',
      lineHeight: 1.25,
    },
    {
      id: 'date',
      label: 'Datum',
      type: 'text',
      required: false,
      maxLength: 50,
      fontSize: 14,
      x: 70,
      y: 920,
      width: 400,
      height: 30,
      fontFamily: 'FF DIN',
      fontWeight: '500',
      color: '#FFFACD',
      textAlign: 'left',
    },
  ],
  logo: {
    text: 'BREAKING',
    x: 920,
    y: 115,
    fontSize: 20,
    color: '#FFFFFF',
  },
}
