import { TemplateConfig } from '../types/template'

export const carouselTemplate: TemplateConfig = {
  id: 'carousel',
  name: 'Carousel Slide',
  description: 'Voor Instagram carousel posts',
  backgroundColor: '#FFFFFF',
  fields: [
    {
      id: 'title',
      label: 'Titel',
      type: 'text',
      required: true,
      maxLength: 50,
      maxFontSize: 48,
      minFontSize: 32,
      x: 70,
      y: 80,
      width: 940,
      height: 70,
      fontFamily: 'FF DIN',
      fontWeight: '700',
      color: '#0F0F0F',
      textAlign: 'left',
    },
    {
      id: 'content',
      label: 'Inhoud',
      type: 'multiline',
      required: true,
      maxFontSize: 30,
      minFontSize: 14,
      x: 70,
      y: 180,
      width: 940,
      height: 400,
      fontFamily: 'FF DIN',
      fontWeight: '500',
      color: '#2C2C2C',
      textAlign: 'left',
      lineHeight: 1.6,
    },
    {
      id: 'highlight',
      label: 'Highlight (accent)',
      type: 'text',
      required: false,
      maxLength: 60,
      fontSize: 24,
      x: 70,
      y: 620,
      width: 940,
      height: 50,
      fontFamily: 'FF DIN',
      fontWeight: '700',
      color: '#D32F2F',
      textAlign: 'left',
    },
    {
      id: 'slideNumber',
      label: 'Slide nummer',
      type: 'text',
      required: false,
      maxLength: 10,
      fontSize: 14,
      x: 920,
      y: 920,
      width: 90,
      height: 30,
      fontFamily: 'FF DIN',
      fontWeight: '400',
      color: '#999999',
      textAlign: 'right',
    },
  ],
  borderRadius: 16,
}
