import { TemplateConfig } from '../types/template'

export const carouselTemplate: TemplateConfig = {
  id: 'carousel',
  name: 'Carousel Slide',
  description: 'Voor Instagram carousel posts',
  backgroundColor: '#FFFFFF',
  fields: [
    {
      id: 'title',
      label: 'Titel',
      type: 'text',
      required: true,
      maxLength: 50,
      maxFontSize: 44,
      minFontSize: 28,
      x: 60,
      y: 80,
      width: 960,
      height: 70,
      fontFamily: 'FF DIN',
      fontWeight: '700',
      color: '#1A1A1A',
      textAlign: 'left',
    },
    {
      id: 'content',
      label: 'Inhoud',
      type: 'multiline',
      required: true,
      maxFontSize: 32,
      minFontSize: 16,
      x: 60,
      y: 180,
      width: 960,
      height: 400,
      fontFamily: 'FF DIN',
      fontWeight: '400',
      color: '#333333',
      textAlign: 'left',
      lineHeight: 1.6,
    },
    {
      id: 'highlight',
      label: 'Highlight (bold)',
      type: 'text',
      required: false,
      maxLength: 60,
      fontSize: 24,
      x: 60,
      y: 620,
      width: 960,
      height: 50,
      fontFamily: 'FF DIN',
      fontWeight: '700',
      color: '#E74C3C',
      textAlign: 'left',
    },
    {
      id: 'slideNumber',
      label: 'Slide nummer',
      type: 'text',
      required: false,
      maxLength: 10,
      fontSize: 16,
      x: 900,
      y: 920,
      width: 120,
      height: 30,
      fontFamily: 'FF DIN',
      fontWeight: '400',
      color: '#95A5A6',
      textAlign: 'right',
    },
  ],
  borderRadius: 12,
}
