import { TemplateConfig } from '../types/template'

export const quoteTemplate: TemplateConfig = {
  id: 'quote',
  name: 'Quote Post',
  description: 'Een opvallend design voor inspirerende citaten',
  backgroundColor: '#0F0F0F',
  fields: [
    {
      id: 'quote',
      label: 'Citaat',
      type: 'multiline',
      required: true,
      maxFontSize: 56,
      minFontSize: 28,
      x: 80,
      y: 150,
      width: 920,
      height: 320,
      fontFamily: 'FF DIN',
      fontWeight: '700',
      color: '#FFFFFF',
      textAlign: 'center',
      lineHeight: 1.3,
    },
    {
      id: 'author',
      label: 'Auteur',
      type: 'text',
      required: true,
      maxLength: 100,
      fontSize: 22,
      x: 80,
      y: 500,
      width: 920,
      height: 40,
      fontFamily: 'FF DIN',
      fontWeight: '600',
      color: '#E8E8E8',
      textAlign: 'center',
    },
    {
      id: 'subtitle',
      label: 'Subtitel (optioneel)',
      type: 'text',
      required: false,
      maxLength: 100,
      fontSize: 16,
      x: 80,
      y: 570,
      width: 920,
      height: 35,
      fontFamily: 'FF DIN',
      fontWeight: '500',
      color: '#999999',
      textAlign: 'center',
    },
  ],
  logo: {
    text: 'HHC',
    x: 950,
    y: 1020,
    fontSize: 12,
    color: '#555555',
  },
}
