import { TemplateConfig } from '../types/template'

export const quoteTemplate: TemplateConfig = {
  id: 'quote',
  name: 'Quote Post',
  description: 'Een opvallend design voor inspirerende citaten',
  backgroundColor: '#1a1a1a',
  fields: [
    {
      id: 'quote',
      label: 'Citaat',
      type: 'multiline',
      required: true,
      maxFontSize: 48,
      minFontSize: 24,
      x: 60,
      y: 100,
      width: 960,
      height: 350,
      fontFamily: 'Georgia',
      fontWeight: '600',
      color: '#FFFFFF',
      textAlign: 'center',
      lineHeight: 1.4,
    },
    {
      id: 'author',
      label: 'Auteur',
      type: 'text',
      required: true,
      maxLength: 100,
      fontSize: 24,
      x: 60,
      y: 480,
      width: 960,
      height: 50,
      fontFamily: 'Arial',
      fontWeight: '400',
      color: '#B0B0B0',
      textAlign: 'center',
    },
    {
      id: 'subtitle',
      label: 'Subtitel (optioneel)',
      type: 'text',
      required: false,
      maxLength: 100,
      fontSize: 18,
      x: 60,
      y: 560,
      width: 960,
      height: 40,
      fontFamily: 'Arial',
      fontWeight: '400',
      color: '#808080',
      textAlign: 'center',
    },
  ],
  logo: {
    text: '© LOGO',
    x: 900,
    y: 1000,
    fontSize: 14,
    color: '#606060',
  },
}
