import { ThumbnailConfig } from '../types/template'

export const thumbnailTemplate: ThumbnailConfig = {
  id: 'hhc-eyecons-thumbnail',
  name: 'HHC Eyecons Thumbnail',
  description: '1920x1080 Video Thumbnail met foto, naam en quote',
  canvasWidth: 1920,
  canvasHeight: 1080,
  sidebarWidth: 28,
  sidebarColor: '#ff6f00',
  nameLabel: {
    x: 98,
    y: 706,
    width: 589,
    height: 92,
    backgroundColor: '#000000',
    textColor: '#ffffff',
    fontSize: 48,
    fontFamily: 'FF DIN',
    fontWeight: '700',
    paddingLeft: 35,
    paddingRight: 35,
  },
  quote: {
    openingQuoteX: 98,
    openingQuoteY: 818,
    openingQuoteFontSize: 80,
    x: 131,
    y: 831,
    maxWidth: 951,
    fontSize: 84,
    fontFamily: 'FF DIN',
    fontWeight: '900',
    textColor: '#ffffff',
    lineHeight: 0.95,
    shadowOffsetX: 5,
    shadowOffsetY: 6,
    shadowBlur: 4,
    shadowColor: 'rgba(0, 0, 0, 0.6)',
  },
}
